
package com.camilo.tarjetadigital.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TarjetaServiceImplService", targetNamespace = "http://service.tarjetaDigital.camilo.com/", wsdlLocation = "http://tarjetadigital123.herokuapp.com/TarjetaService?wsdl")
public class TarjetaServiceImplService
    extends Service
{

    private final static URL TARJETASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TARJETASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TARJETASERVICEIMPLSERVICE_QNAME = new QName("http://service.tarjetaDigital.camilo.com/", "TarjetaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tarjetadigital123.herokuapp.com/TarjetaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TARJETASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TARJETASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TarjetaServiceImplService() {
        super(__getWsdlLocation(), TARJETASERVICEIMPLSERVICE_QNAME);
    }

    public TarjetaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TARJETASERVICEIMPLSERVICE_QNAME, features);
    }

    public TarjetaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TARJETASERVICEIMPLSERVICE_QNAME);
    }

    public TarjetaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TARJETASERVICEIMPLSERVICE_QNAME, features);
    }

    public TarjetaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TarjetaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TarjetaService
     */
    @WebEndpoint(name = "TarjetaServiceImplPort")
    public TarjetaService getTarjetaServiceImplPort() {
        return super.getPort(new QName("http://service.tarjetaDigital.camilo.com/", "TarjetaServiceImplPort"), TarjetaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TarjetaService
     */
    @WebEndpoint(name = "TarjetaServiceImplPort")
    public TarjetaService getTarjetaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.tarjetaDigital.camilo.com/", "TarjetaServiceImplPort"), TarjetaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TARJETASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TARJETASERVICEIMPLSERVICE_EXCEPTION;
        }
        return TARJETASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
