
package com.camilo.tarjetadigital.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TarjetaService", targetNamespace = "http://service.tarjetaDigital.camilo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TarjetaService {


    /**
     * 
     * @return
     *     returns java.util.List<com.camilo.tarjetadigital.service.Tarjeta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTodas", targetNamespace = "http://service.tarjetaDigital.camilo.com/", className = "com.camilo.tarjetadigital.service.ObtenerTodas")
    @ResponseWrapper(localName = "obtenerTodasResponse", targetNamespace = "http://service.tarjetaDigital.camilo.com/", className = "com.camilo.tarjetadigital.service.ObtenerTodasResponse")
    public List<Tarjeta> obtenerTodas();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.camilo.tarjetadigital.service.Tarjeta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearTarjeta", targetNamespace = "http://service.tarjetaDigital.camilo.com/", className = "com.camilo.tarjetadigital.service.CrearTarjeta")
    @ResponseWrapper(localName = "crearTarjetaResponse", targetNamespace = "http://service.tarjetaDigital.camilo.com/", className = "com.camilo.tarjetadigital.service.CrearTarjetaResponse")
    public Tarjeta crearTarjeta(
        @WebParam(name = "arg0", targetNamespace = "")
        Tarjeta arg0);

}
